### PR TITLE
[#9] Test suite in container

### PR DESCRIPTION
**Pull request by GuChad369**
Update the test suite to run in a single container.

The only issue is the time consumption.

If you want to test, please replace line 79 in `Dockerfile.rocky9` with:

``` Dockerfile
RUN git clone --branch "test" --single-branch --depth 1 https://github.com/GuChad369/pgmoneta_ext && \
```

Test result:
Screenshot 2024-07-12 at 6 32 31 PM

### CODE REVIEW

**Comment by jesperpedersen** [comment]
@GuChad369 Did you try to checkout the repository once, and switch between branches between the runs ?

**Comment by jesperpedersen** [comment]
Maybe it isn't possible though...

**Comment by GuChad369** [comment]
If we can test them in parallel, the time will be significantly reduced. Currently, the tests run sequentially. I am trying to find a way to make them run simultaneously. This will greatly improve the efficiency.

**Comment by jesperpedersen** [comment]
yes, as long as we have the logs from each

**Comment by GuChad369** [comment]
There is an option `ctest -j` which can run the tests in parallel using the given number of jobs. The time cost will depend on the machine. On my computer, it takes 600 seconds, whereas before it took 1200 seconds, effectively reducing the time by half.
Screenshot 2024-07-13 at 10 54 26 AM

**Comment by jesperpedersen** [comment]
```
ctest -j 4
Test project ..../pgmoneta_ext/build
    Start 1: test_version_13_rocky9
    Start 2: test_version_14_rocky9
    Start 3: test_version_15_rocky9
    Start 4: test_version_16_rocky9
1/4 Test #1: test_version_13_rocky9 ...........***Failed  152.69 sec
2/4 Test #2: test_version_14_rocky9 ...........***Failed  152.69 sec
3/4 Test #3: test_version_15_rocky9 ...........   Passed  414.99 sec
4/4 Test #4: test_version_16_rocky9 ...........   Passed  424.51 sec

50% tests passed, 2 tests failed out of 4

Total Test time (real) = 424.52 sec

The following tests FAILED:
	  1 - test_version_13_rocky9 (Failed)
	  2 - test_version_14_rocky9 (Failed)
Errors while running CTest

```

**Comment by jesperpedersen** [comment]
[LastTest.log](https://github.com/user-attachments/files/16203061/LastTest.log)

**Comment by GuChad369** [comment]
The problem with the two failed tests is:
``` log
"f4952f7dfb0d1c67ab07e600f4f0a989e356e58c49ea03a20374cce67f90610d" to file: reading tar archive: copying content for "usr/share/doc/strace/NEWS": write /var/tmp/buildah2479751812/layer: no space left on device on pipe close
```

This issue is related to a lack of space and has nothing to do with the source code.

And if you want to test, please replace line 79 in Dockerfile.rocky9 with:
```dockerfile
RUN git clone --branch "test" --single-branch --depth 1 https://github.com/GuChad369/pgmoneta_ext && \
```

**Comment by jesperpedersen** [comment]
On the host ?

```
/dev/nvme0n1p2    30G   20G  8.7G  70% /
```

8.7G should be more than enough

**Comment by jesperpedersen** [comment]
And, `/home` is

```
/dev/nvme0n1p5   869G  796G   30G  97% /home
```

**Comment by GuChad369** [comment]
Please replace the line and retest. The main repository won’t work until this PR is merged.

**Comment by jesperpedersen** [comment]
Merged.

Thanks for your contribution !

**Pull request merged**
